---
- name: Install Python3
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Create ATM directory
  file:
    path: /opt/atm_sim
    state: directory

# Ansible looks in provisioning/roles/atm_host/files/
- name: Copy atm_sim.py from role files
  copy:
    src: atm_sim.py
    dest: /opt/atm_sim/atm_sim.py
    mode: '0755'

- name: Create Systemd Service to keep ATM Simulator running
  copy:
    dest: /etc/systemd/system/atm_sim.service
    content: |
      [Unit]
      Description=IronVault ATM Simulator
      After=network.target
      [Service]
      User=root
      WorkingDirectory=/opt/atm_sim
      ExecStart=/usr/bin/python3 /opt/atm_sim/atm_sim.py
      Restart=always
      [Install]
      WantedBy=multi-user.target

- name: Start and enable the ATM Simulator service
  systemd:
    name: atm_sim
    state: started
    enabled: yes
