---
# Basic configuration of all defined devices
- name: Basic Initialization
  hosts: server, victim, attacker
  become: yes
  roles: 
    - hosts

- name: Configure Kali
  hosts: attacker
  become: yes
  roles:
    - attacker

- name: Configure Vulnerable Systems
  hosts: server, victim
  become: yes
  roles:
    - vulnerable-systems

- name: set up command logging
  hosts: 
    - routers
    - hosts
  become: yes
  roles:
    - role: sandbox-logging
      slf_destination_port: '{% if hostvars["man"] is defined -%} 514 {%- else -%} 515 {%- endif %}'
      when: ansible_system == "Linux"
