---
- name: Setup Web Server (DMZ)
  hosts: web-ubuntu, internal-db
  become: yes
  roles:
    - web-ubuntu
    - internal_database

- name: Setup ATM Host and Docker
  hosts: atm-controller
  become: yes
  roles:
    - atm_controller

- name: Setup Internal DC
  hosts: internal-dc
  roles:
    - internal_dc

- name: Setup Internal Windows Server
  hosts: internal-windows
  roles:
    - internal_windows

- name: Setup Kali
  hosts: kali
  become: yes
  roles:
    - kali

- name: Configure Core Router
  hosts: core-router
  become: yes
  roles:
    - core-router
