---
# Basic configuration of all defined devices
- name: Basic Itialization
  hosts: all
  become: yes
  roles: 
    - role:hosts

- name: Configure Kali
  hosts: attacker
  become: yes
  roles:
    role: attacker

- name: Configure Vulnerable Systems
  hosts: server, victim
  become: yes
  roles:
    role: vulnerable-systems
